mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.sy.doc.model
server:
  context-path: /
  port: 8080
spring:
  application:
    name: doc-manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/doc_manager?characterEncoding=utf-8&useSSL=false
    username: root