package com.sy.doc.model;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated Sun May 17 20:26:21 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbg.generated Sun May 17 20:26:21 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.permission_list
     *
     * @mbg.generated Sun May 17 20:26:21 CST 2020
     */
    private String permissionList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbg.generated Sun May 17 20:26:21 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbg.generated Sun May 17 20:26:21 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbg.generated Sun May 17 20:26:21 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbg.generated Sun May 17 20:26:21 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.permission_list
     *
     * @return the value of role.permission_list
     *
     * @mbg.generated Sun May 17 20:26:21 CST 2020
     */
    public String getPermissionList() {
        return permissionList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.permission_list
     *
     * @param permissionList the value for role.permission_list
     *
     * @mbg.generated Sun May 17 20:26:21 CST 2020
     */
    public void setPermissionList(String permissionList) {
        this.permissionList = permissionList;
    }
}